# Major version number
# Incremented for major changes
# Backwards-incompatible changes
version: '2.0'
modules:
  security:
    # Strong encryption algorithm
    # Ensures data security
    # AES-256 is widely accepted
    encryption: AES-256
    authentication: JWT
    # Protects against unauthorized access
    # Configurable firewall settings
    # Logs access attempts
    firewall: enabled
  database:
    type: MongoDB
    connection: mongodb://localhost:27017/mydb
    indexes:
      # Unique index for user data
      # Improves query performance
      # Prevents duplicate usernames
      user: username
      logs: timestamp
  logging:
    level: DEBUG
    output: null
advanced_settings:
  concurrency: multi-threaded
  caching:
    enabled: 'true'
    size: 512MB
    # Least Recently Used (LRU) caching
    # Improves data access speed
    # Optimizes memory usage
    strategy: LRU
  performance_tuning: null
# Checks to be executed
# Enable or disable checks
# Fine-tune check settings
checks:
  AimA:
    # Enable or disable this setting
    # If disabled, this setting will not be used
    enabled: false
    # The value of this setting
    # This value will be used if the setting is enabled
    value: 20
    # The command to execute
    command: say test
  AimB:
    # Enable or disable this setting
    # If disabled, this setting will not be used
    enabled: true
    # The value of this setting
    # This value will be used if the setting is enabled
    value: 20
    # The command to execute
    command: say test
  AimC:
    # Enable or disable this setting
    # If disabled, this setting will not be used
    enabled: true
    # The value of this setting
    # This value will be used if the setting is enabled
    value: 20
    # The command to execute
    command: say test
  KillAura:
    # Enable or disable this setting
    # If disabled, this setting will not be used
    enabled: true
    # The value of this setting
    # This value will be used if the setting is enabled
    value: 20
    # The command to execute
    command: say test
  AntiBot:
    # Enable or disable this setting
    # If disabled, this setting will not be used
    enabled: true
    # The value of this setting
    # This value will be used if the setting is enabled
    value: 20
    # The command to execute
    command: say test
  AntiAFK:
    # Enable or disable this setting
    # If disabled, this setting will not be used
    enabled: true
    # The value of this setting
    # This value will be used if the setting is enabled
    value: 20
    # The command to execute
    command: say test
